name: Tests

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@master
      - name: Install deps
        run: bash ./scripts/deps
      - name: Build
        run: bash ./scripts/install
      - name: Test
        run: bash ./scripts/test
